### ISSUE TITLE
random freeze while MCMT is installed

### ISSUE THREAD

**Issue by TropheusJ** [jediminer543/JMT-MCMT#17]
occasionally for no obvious reason the game will freeze, not crash. this appears to only happen with MCMT installed. latest log is attached if I did it right, no crashlog is made.
[latest.txt](https://github.com/jediminer543/JMT-MCMT/files/5250898/latest.txt)
1.15.2, forge 31.2.41,  jmt_mcmt-1.15.2-0.16.50. other mods should be in the log if I'm not mistaken.

**Comment by jediminer543** [comment]
Ok, apparenly I missed this in triage, this is kinda an important thing and I should have noticed it sooner

Will poke

If you can try and repro with 0.17.x that would help but shouldn't change the bug as it hasn't touched that code

**Comment by TropheusJ** [comment]
I was flying around and the game crashed saying "Exception generating new chunk". I have zero clue if this is even related to MCMT or not, but here's the log and crashlog anyway. I should mention that I have made changes to the pack since I made this issue.
[crash-2020-10-02_19.16.32-server.txt](https://github.com/jediminer543/JMT-MCMT/files/5320715/crash-2020-10-02_19.16.32-server.txt)
[latest.log](https://github.com/jediminer543/JMT-MCMT/files/5320717/latest.log)

**Comment by jediminer543** [comment]
Just to add info for future me:

Relevent section is:

```
java.util.ConcurrentModificationException
 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
 	at java.util.HashMap$EntryIterator.next(HashMap.java:1463)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1461)
 	at net.minecraft.util.ClassInheritanceMultiMap.remove(SourceFile:39)
```

This should have already been patched in a transformer, so the fact it persists means that transformer was brazenly subpar (or maybe is version specific as this is only seen in 1.15.2)

**Comment by TropheusJ** [comment]
![image](https://user-images.githubusercontent.com/60247969/94977156-80cef200-04e5-11eb-9a2b-a4199bb490b9.png)
oh boy, 99% sure reloading the world got some chunk corruption. pretty sure this used to be a straight line.

**Comment by TropheusJ** [comment]
got the same crash while generating the same area. going to try a fresh world.

**Comment by TropheusJ** [comment]
good news: MCMT is not the culprit for that crash. removed it and still happens.

**Comment by jediminer543** [comment]
That's RE: world corruption bug right?

If so that's very good, as I like not causing world corruption

**Comment by TropheusJ** [comment]
not sure about corruption, I haven't seen any new chunks corrupt after 2 more crashes, so it seems maybe I just somehow missed them and they were there all along. will say something if it happens again. I can guarantee that MCMT did not cause that crash though. need to figure out the cause of this crash to continue testing now, will get back to you.

**Comment by TropheusJ** [comment]
could not reproduce with 1.15.2-0.17.52. think I stress tested enough? however, the pack has been changed since I made this issue, so it may have been a mod incompatibility. going to test on 1.15.2-0.16.50 and see if it occurs. if it does, great! its fixed. if it doesn't, well, I have no idea how I would find the incompatible mod. 
![2020-10-02_20 55 43](https://user-images.githubusercontent.com/60247969/94979666-14a6bb00-04f2-11eb-8796-a8f5346584ed.png)

**Comment by TropheusJ** [comment]
it appears to have been fixed? that world I used to stress test froze after less than a second, and a fresh one barely lasted 2 before freezing. updated back to 1.15.2-0.17.52 and it works fine.

**Comment by jediminer543** [comment]
Try again with 0.17.54; for reasons that are complicated 0.17.52 was very borked and didn't actually load properly
