### ISSUE TITLE
[Serverspam] TPS dips too much when using this mod inconjunction with iguanatweaks.

### ISSUE THREAD

**Issue by Cixon** [jediminer543/JMT-MCMT#57]
**Repercussions:** I have a handful of mods installed onto the server. Some I will mention are Sereneseasons (latest as rn), BiomesYoullGo, Iguanatweaks, and of course MCMT.

**BUG:** The console gets spammed constantly non stop with the long code pasted down below. Very annoying and lags the server.

**Context:** I did try and disable the crop feature from Iguanatweaks entire via config but this fail and did nothing.
Only config settings I changed from the default via MCMT was disableWorld = true and disableEntity = true.

### - Error spammed on the server -

02:17:33] [MCMT-Pool-Thread-79/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: insane96mcp/iguanatweaksreborn/modules/farming/feature/CropsGrowthFeature
        Index: 1
        Listeners:
                0: NORMAL
                1: ASM: insane96mcp.iguanatweaksreborn.modules.farming.feature.CropsGrowthFeature@47e4935b cropsRequireWater(Lnet/minecraftforge/event/world/BlockEvent$CropGrowEvent$Pre;)V
                2: ASM: sereneseasons.handler.season.SeasonalCropGrowthHandler@9ed6a3b onCropGrowth(Lnet/minecraftforge/event/world/BlockEvent$CropGrowEvent;)V
java.lang.NoClassDefFoundError: insane96mcp/iguanatweaksreborn/modules/farming/feature/CropsGrowthFeature
        at net.minecraftforge.eventbus.ASMEventHandler_579_CropsGrowthFeature_cropsRequireWater_Pre.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraftforge.common.ForgeHooks.onCropsGrowPre(ForgeHooks.java:1036)
        at net.minecraft.block.AbstractTopPlantBlock.func_225542_b_(AbstractTopPlantBlock.java:35)
        at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227034_b_(AbstractBlock.java:624)
        at net.minecraft.world.server.ServerWorld.func_217441_a(ServerWorld.java:508)
        at org.jmt.mcmt.asmdest.ASMHookTerminator.lambda$callTickEnvironment$5(ASMHookTerminator.java:204)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

>....Exception in thread "MCMT-Pool-Thread-79"
[02:17:33] [MCMT-Pool-Thread-79/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: java.lang.NoClassDefFoundError: insane96mcp/iguanatweaksreborn/modules/farming/feature/CropsGrowthFeature
[02:17:33] [MCMT-Pool-Thread-79/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:        at net.minecraftforge.eventbus.ASMEventHandler_579_CropsGrowthFeature_cropsRequireWater_Pre.invoke(.dynamic)
[02:17:33] [MCMT-Pool-Thread-79/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
[02:17:33] [MCMT-Pool-Thread-79/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
[02:17:33] [MCMT-Pool-Thread-79/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
[02:17:33] [MCMT-Pool-Thread-79/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:        at net.minecraftforge.common.ForgeHooks.onCropsGrowPre(ForgeHooks.java:1036)
[02:17:33] [MCMT-Pool-Thread-79/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:        at net.minecraft.block.AbstractTopPlantBlock.func_225542_b_(AbstractTopPlantBlock.java:35)
[02:17:33] [MCMT-Pool-Thread-79/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:        at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227034_b_(AbstractBlock.java:624)
[02:17:33] [MCMT-Pool-Thread-79/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:        at net.minecraft.world.server.ServerWorld.func_217441_a(ServerWorld.java:508)
[02:17:33] [MCMT-Pool-Thread-79/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:        at org.jmt.mcmt.asmdest.ASMHookTerminator.lambda$callTickEnvironment$5(ASMHookTerminator.java:204)
[02:17:33] [MCMT-Pool-Thread-79/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
[02:17:33] [MCMT-Pool-Thread-79/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[02:17:33] [MCMT-Pool-Thread-79/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[02:17:33] [MCMT-Pool-Thread-79/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[02:17:33] [MCMT-Pool-Thread-79/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[02:17:33] [MCMT-Pool-Thread-79/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by Cixon** [comment]
Mod here: https://www.curseforge.com/minecraft/mc-mods/iguanatweaks-reborn

**Comment by jediminer543** [comment]
Ok, that's an issue that's being fixed in the next update; the beta builds currently have a fix for that

The discord has beta builds auto published there (I should probs make actions put them somewhere else too but \shrug)

I'll try to push them out as a main build soon

**Comment by jediminer543** [comment]
Technically this is a Java 11 issue not an iguana tweaks issue

It's to do with the way classloaders are allocated from what I've been able to gather

**Comment by Cixon** [comment]
> Technically this is a Java 11 issue not an iguana tweaks issue
> 
> It's to do with the way classloaders are allocated from what I've been able to gather

Does this mean it will still be fixed or should I revert back to Java 8?

**Comment by jediminer543** [comment]
Should be yeah

**Comment by jediminer543** [comment]
Just as an added note, the java >8 issue was fixed in the latest release
