### ISSUE TITLE
[Spam Console] Error

### ISSUE THREAD

**Issue by Tealwen** [jediminer543/JMT-MCMT#60]
Server API : Mohist latest
Version: 1.16.5
Version of MCMT : latest on curse

Description:
This Always spam my console !

Error:

`Exception caught during firing event: net/minecraftforge/event/entity/living/LivingSpawnEvent
Console19:40:42
Index: 1
Listeners:
0: HIGHEST
1: ASM: com.oitsjustjose.vtweaks.common.event.mobtweaks.ChallengerMobs@4095a90 registerEvent(Lnet/minecraftforge/event/entity/living/LivingSpawnEvent;)V
2: NORMAL
3: ASM: com.github.alexthe666.alexsmobs.event.ServerEvents@40488070 onEntityDespawnAttempt(Lnet/minecraftforge/event/entity/living/LivingSpawnEvent$AllowDespawn;)V
4: ASM: com.oitsjustjose.vtweaks.common.event.mobtweaks.PeacefulSurface@6d8d368e registerTweak(Lnet/minecraftforge/event/entity/living/LivingSpawnEvent;)V
5: ASM: com.wildcard.buddycards.util.EntitySpawning@1a5ac555 spawnIn(Lnet/minecraftforge/event/entity/living/LivingSpawnEvent;)V
6: ASM: class xratedjunior.betterdefaultbiomes.common.enchantment.EnchantmentEventSubscriber onPlayerTick(Lnet/minecraftforge/event/entity/living/LivingEvent;)V
7: ASM: com.oitsjustjose.vtweaks.common.event.mobtweaks.ChallengerParticles@666c85c8 registerEvent(Lnet/minecraftforge/event/entity/EntityEvent;)V
java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/living/LivingSpawnEvent
at net.minecraftforge.eventbus.ASMEventHandler_791_ChallengerMobs_registerEvent_LivingSpawnEvent.invoke(.dynamic)
at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
19:40:43
Listeners:
0: HIGHEST
1: ASM: com.oitsjustjose.vtweaks.common.event.mobtweaks.ChallengerMobs@4095a90 registerEvent(Lnet/minecraftforge/event/entity/living/LivingSpawnEvent;)V
2: NORMAL
3: ASM: com.github.alexthe666.alexsmobs.event.ServerEvents@40488070 onEntityDespawnAttempt(Lnet/minecraftforge/event/entity/living/LivingSpawnEvent$AllowDespawn;)V
4: ASM: com.oitsjustjose.vtweaks.common.event.mobtweaks.PeacefulSurface@6d8d368e registerTweak(Lnet/minecraftforge/event/entity/living/LivingSpawnEvent;)V
5: ASM: com.wildcard.buddycards.util.EntitySpawning@1a5ac555 spawnIn(Lnet/minecraftforge/event/entity/living/LivingSpawnEvent;)V
6: ASM: class xratedjunior.betterdefaultbiomes.common.enchantment.EnchantmentEventSubscriber onPlayerTick(Lnet/minecraftforge/event/entity/living/LivingEvent;)V
7: ASM: com.oitsjustjose.vtweaks.common.event.mobtweaks.ChallengerParticles@666c85c8 registerEvent(Lnet/minecraftforge/event/entity/EntityEvent;)V
java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/living/LivingSpawnEvent
at net.minecraftforge.eventbus.ASMEventHandler_791_ChallengerMobs_registerEvent_LivingSpawnEvent.invoke(.dynamic)
at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
at net.minecraftforge.event.ForgeEventFactory.canEntityDespawn(ForgeEventFactory.java:220)
at net.minecraft.entity.MobEntity.func_70623_bb(MobEntity.java:716)
at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:552)
at org.jmt.mcmt.asmdest.ASMHookTerminator.lambda$callTick$3(ASMHookTerminator.java:143)
at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)`

**Comment by NXTler** [comment]
Mohist is a really weird beast and we are still working on getting it compatible with MCMT. The newest dev-version of MCMT on the discord solves "all" problems (as far as I tested). Sometimes one specific mohist version don't like MCMT for some reason, so you have to try around a bit with older versions.

**Comment by KubiRemPL** [comment]
Yeah just try latest version form github (or compile it yourself).
